name: Auto release

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Modify
        run: |
          echo "Hello, World" >> hello
      - name: Config git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
      - name: Commit
        run: |
          git add .
          git commit -m "update"
      - name: "Push"
        run: |
          git push origin master